[2025-04-23T05:01:29.499+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T05:01:29.518+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-04-23T05:01:28.984134+00:00 [queued]>
[2025-04-23T05:01:29.528+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-04-23T05:01:28.984134+00:00 [queued]>
[2025-04-23T05:01:29.529+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-23T05:01:29.544+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2025-04-23 05:01:28.984134+00:00
[2025-04-23T05:01:29.554+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2025-04-23T05:01:28.984134+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpaxx8v1a8']
[2025-04-23T05:01:29.558+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask dbt_run
[2025-04-23T05:01:29.559+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=874) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T05:01:29.560+0000] {standard_task_runner.py:72} INFO - Started process 875 to run task
[2025-04-23T05:01:29.603+0000] {task_command.py:467} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2025-04-23T05:01:28.984134+00:00 [running]> on host 0b555a0ed01e
[2025-04-23T05:01:29.730+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T05:01:28.984134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T05:01:28.984134+00:00'
[2025-04-23T05:01:29.731+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T05:01:29.757+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-23T05:01:29.760+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-04-23T05:01:29.768+0000] {subprocess.py:86} INFO - Output:
[2025-04-23T05:01:32.911+0000] {subprocess.py:93} INFO - [0m05:01:32  Running with dbt=1.6.18
[2025-04-23T05:01:33.700+0000] {subprocess.py:93} INFO - [0m05:01:33  Registered adapter: snowflake=1.6.0
[2025-04-23T05:01:33.898+0000] {subprocess.py:93} INFO - [0m05:01:33  Found 2 tests, 2 models, 2 sources, 0 exposures, 0 metrics, 375 macros, 0 groups, 0 semantic models
[2025-04-23T05:01:33.900+0000] {subprocess.py:93} INFO - [0m05:01:33
[2025-04-23T05:01:36.298+0000] {subprocess.py:93} INFO - [0m05:01:36  Concurrency: 1 threads (target='dev')
[2025-04-23T05:01:36.300+0000] {subprocess.py:93} INFO - [0m05:01:36
[2025-04-23T05:01:36.313+0000] {subprocess.py:93} INFO - [0m05:01:36  1 of 2 START sql view model analytics.law_enforcement_calls .................... [RUN]
[2025-04-23T05:01:37.799+0000] {subprocess.py:93} INFO - [0m05:01:37  1 of 2 OK created sql view model analytics.law_enforcement_calls ............... [[32mSUCCESS 1[0m in 1.48s]
[2025-04-23T05:01:37.802+0000] {subprocess.py:93} INFO - [0m05:01:37  2 of 2 START sql view model analytics.Avg_response_time_pd ..................... [RUN]
[2025-04-23T05:01:40.016+0000] {subprocess.py:93} INFO - [0m05:01:40  2 of 2 ERROR creating sql view model analytics.Avg_response_time_pd ............ [[31mERROR[0m in 2.21s]
[2025-04-23T05:01:40.029+0000] {subprocess.py:93} INFO - [0m05:01:40
[2025-04-23T05:01:40.030+0000] {subprocess.py:93} INFO - [0m05:01:40  Finished running 2 view models in 0 hours 0 minutes and 6.13 seconds (6.13s).
[2025-04-23T05:01:40.068+0000] {subprocess.py:93} INFO - [0m05:01:40
[2025-04-23T05:01:40.069+0000] {subprocess.py:93} INFO - [0m05:01:40  [31mCompleted with 1 error and 0 warnings:[0m
[2025-04-23T05:01:40.070+0000] {subprocess.py:93} INFO - [0m05:01:40
[2025-04-23T05:01:40.071+0000] {subprocess.py:93} INFO - [0m05:01:40    Database Error in model Avg_response_time_pd (models/output/Avg_response_time_pd.sql)
[2025-04-23T05:01:40.072+0000] {subprocess.py:93} INFO -   001003 (42000): SQL compilation error:
[2025-04-23T05:01:40.072+0000] {subprocess.py:93} INFO -   syntax error line 16 at position 2 unexpected ')'.
[2025-04-23T05:01:40.073+0000] {subprocess.py:93} INFO -   compiled Code at target/run/lab2_dbt/models/output/Avg_response_time_pd.sql
[2025-04-23T05:01:40.074+0000] {subprocess.py:93} INFO - [0m05:01:40
[2025-04-23T05:01:40.075+0000] {subprocess.py:93} INFO - [0m05:01:40  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
[2025-04-23T05:01:41.289+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-23T05:01:41.301+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-23T05:01:41.308+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2025-04-23T05:01:28.984134+00:00, execution_date=20250423T050128, start_date=20250423T050129, end_date=20250423T050141
[2025-04-23T05:01:41.323+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T05:01:41.324+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 60 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 875)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-23T05:01:41.358+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-23T05:01:41.392+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T05:01:41.397+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
